apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-irri
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0047-tenant/tkrw-pr712-0075-0047-app/devfile-sample-irri@sha256:171aa3f68fb669f8f8f563edbb54a075ddbbccdea2c47f6689bba3928797bde4
        name: my-nodejs
        resources: {}
status: {}
